name = "echobell-one"
compatibility_date = "2025-03-17"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[[d1_databases]]
binding = "DB"
database_name = "echobell"
database_id = "42f866b5-2d88-4364-b41c-51669cd88644"

[observability]
enabled = true
head_sampling_rate = 1
