/**
 * Custom worker entry: wraps the SvelteKit-generated worker and adds the
 * /api/og image endpoint. The OG renderer (satori + resvg) relies on wasm
 * modules that must be bundled by wrangler rather than Vite, which is why
 * this lives outside the SvelteKit build.
 *
 * The SvelteKit worker is emitted by @sveltejs/adapter-cloudflare to
 * .svelte-kit/cloudflare/_worker.js (see wrangler.adapter.jsonc).
 */
// @ts-expect-error -- generated by `pnpm build`, untyped
import svelteKitWorker from "../../.svelte-kit/cloudflare/_worker.js";
import { handleOgRequest } from "./og";

interface Env {
  DB: unknown;
  ASSETS: { fetch: typeof fetch };
}

export default {
  async fetch(
    request: Request,
    env: Env,
    ctx: ExecutionContext
  ): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === "/api/og") {
      try {
        return await handleOgRequest(request);
      } catch (error) {
        console.error("OG image generation failed:", error);
        return new Response("Failed to generate image", { status: 500 });
      }
    }

    return svelteKitWorker.fetch(request, env, ctx);
  },
} satisfies ExportedHandler<Env>;
